name: Demo

on:
# WEBHOOK EVENT#
  push:
    branches:
      - main
      - Task/*
      - feat/*
  pull_request:
    branches:
      - main

# schedule event
  schedule:
    - cron: 0 12 * * *
    - cron: 0 9 * * 0
# manual event
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good? "
        type: boolean
        default: true
  issues:
    types:
      - opened
      - closed

## ENVIRONMENT##
env:
  MY_GREETING: HELLO
  MY_NAME: SURAJ
jobs:
  Job1:
    runs-on: ubuntu-latest
    # steps:
    #   - name: Step1:${{ env.MY_GREETING }} ${{ env.MY_NAME }} Chai Pi  !!
    #     run: echo "$MY_NAME is learning Github Actions"
    #     if: ${{ env.MY_NAME == 'SURAJ'}} # [WARNING] Double quote is not allowed
    steps:
      - name: Step1:${{ env.MY_GREETING }} ${{ env.MY_NAME }} Chai Pi  !!
        run: echo "$MY_NAME is learning Github Actions"
        if: ${{ env.MY_NAME == 'NILESH'}} # [WARNING] Double quote is not allowed

  Job2:
    runs-on: ubuntu-latest
    env:
      MY_NAME: Suraj Bhai
    needs: [Job1]
    steps:
      - name: Step2:Thik hai ${{ env.MY_NAME }} Chai Pila do
        run: echo "This is step2 with Need of Job1"

      - name: Step3:Or batao kya chal rha hai
        if: ${{ inputs.areYouFeelingGood }}
        run: echo "I am doing good"

      - name: Step3:Or batao kya chal rha hai
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "I am not doing well!! but thanks for asking"

      - name: step4
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "Please take Sick Leave"

  Job3:
    runs-on: ubuntu-latest
    needs: [Job2]
    steps:
      - name: Step4:Office aane ka kya scene hai
        if: ${{ inputs.areYouFeelingGood }}
        run: echo "Office aane wale hai!!"

      - name: Step4:Office aane ka kya scene hai
        if: ${{ !inputs.areYouFeelingGood }}
        run: echo "Mail Dal dete hai"
